const neighborhoods = [
  { name: 'Agronomía', url: 'agronomia' },
  { name: 'Almagro', url: 'almagro' },
  { name: 'Balvanera', url: 'balvanera' },
  { name: 'Barracas', url: 'barracas' },
  { name: 'Belgrano', url: 'belgrano' },
  { name: 'Boedo', url: 'boedo' },
  { name: 'Caballito', url: 'caballito' },
  { name: 'Chacarita', url: 'chacarita' },
  { name: 'Coghlan', url: 'coghlan' },
  { name: 'Colegiales', url: 'colegiales' },
  { name: 'Constitución', url: 'constitucion' },
  { name: 'Flores', url: 'flores' },
  { name: 'Floresta', url: 'floresta' },
  { name: 'La Boca', url: 'la-boca' },
  { name: 'La Paternal', url: 'la-paternal' },
  { name: 'Liniers', url: 'liniers' },
  { name: 'Mataderos', url: 'mataderos' },
  { name: 'Monte Castro', url: 'monte-castro' },
  { name: 'Montserrat', url: 'montserrat' },
  { name: 'Nueva Pompeya', url: 'nueva-pompeya' },
  { name: 'Nuñez', url: 'nunez' },
  { name: 'Palermo', url: 'palermo' },
  { name: 'Parque Avellaneda', url: 'parque-avellaneda' },
  { name: 'Parque Chacabuco', url: 'parque-chacabuco' },
  { name: 'Parque Chas', url: 'parque-chas' },
  { name: 'Parque Patricios', url: 'parque-patricios' },
  { name: 'Puerto Madero', url: 'puerto-madero' },
  { name: 'Recoleta', url: 'recoleta' },
  { name: 'Retiro', url: 'retiro' },
  { name: 'Saavedra', url: 'saavedra' },
  { name: 'San Cristóbal', url: 'san-cristobal' },
  { name: 'San Nicolás', url: 'san-nicolás' },
  { name: 'San Telmo', url: 'san-telmo' },
  { name: 'Versalles', url: 'versalles' },
  { name: 'Villa Crespo', url: 'villa-crespo' },
  { name: 'Villa Devoto', url: 'villa-devoto' },
  { name: 'Villa General Mitre', url: 'villa-general-mitre' },
  { name: 'Villa Lugano', url: 'villa-lugano' },
  { name: 'Villa Luro', url: 'villa-luro' },
  { name: 'Villa Ortúzar', url: 'villa-ortuzar' },
  { name: 'Villa Pueyrredón', url: 'villa-pueyrredon' },
  { name: 'Villa Real', url: 'villa-real' },
  { name: 'Villa Riachuelo', url: 'villa-riachuelo' },
  { name: 'Villa Santa Rita', url: 'villa-santa-rita' },
  { name: 'Villa Soldati', url: 'villa-soldati' },
  { name: 'Villa Urquiza', url: 'villa-urquiza' },
  { name: 'Villa del Parque', url: 'villa-del-parque' },
  { name: 'Vélez Sarsfield', url: 'villa-del-parque' }
]

export default neighborhoods
