const neighborhoods = [
  { name: 'Agronomía', url: 'agronomia', telexplorerId: 121341211, type: 'neighborhood' },
  { name: 'Almagro', url: 'almagro', telexplorerId: 121341212, type: 'neighborhood' },
  { name: 'Balvanera', url: 'balvanera', telexplorerId: 121341213, type: 'neighborhood' },
  { name: 'Barracas', url: 'barracas', telexplorerId: 121341214, type: 'neighborhood' },
  { name: 'Belgrano', url: 'belgrano', telexplorerId: 121341215, type: 'neighborhood' },
  { name: 'Boedo', url: 'boedo', telexplorerId: 121341217, type: 'neighborhood' },
  { name: 'Caballito', url: 'caballito', telexplorerId: 121341218, type: 'neighborhood' },
  { name: 'Chacarita', url: 'chacarita', telexplorerId: 121341219, type: 'neighborhood' },
  { name: 'Coghlan', url: 'coghlan', telexplorerId: 121341220, type: 'neighborhood' },
  { name: 'Colegiales', url: 'colegiales', telexplorerId: 121341221, type: 'neighborhood' },
  { name: 'Constitución', url: 'constitucion', telexplorerId: 121341222, type: 'neighborhood' },
  { name: 'Flores', url: 'flores', telexplorerId: 121341223, type: 'neighborhood' },
  { name: 'Floresta', url: 'floresta', telexplorerId: 121341224, type: 'neighborhood' },
  { name: 'La Boca', url: 'la-boca', telexplorerId: 121341216, type: 'neighborhood' },
  { name: 'La Paternal', url: 'la-paternal', telexplorerId: 121341225, type: 'neighborhood' },
  { name: 'Liniers', url: 'liniers', telexplorerId: 121341226, type: 'neighborhood' },
  { name: 'Mataderos', url: 'mataderos', telexplorerId: 121341227, type: 'neighborhood' },
  { name: 'Monte Castro', url: 'monte-castro', telexplorerId: 121341229, type: 'neighborhood' },
  { name: 'Montserrat', url: 'montserrat', telexplorerId: 121341228, type: 'neighborhood' },
  { name: 'Nueva Pompeya', url: 'nueva-pompeya', telexplorerId: 121341230, type: 'neighborhood' },
  { name: 'Nuñez', url: 'nunez', telexplorerId: 121341231, type: 'neighborhood' },
  { name: 'Palermo', url: 'palermo', telexplorerId: 121341232, type: 'neighborhood' },
  { name: 'Parque Avellaneda', url: 'parque-avellaneda', telexplorerId: 121341233, type: 'neighborhood' },
  { name: 'Parque Chacabuco', url: 'parque-chacabuco', telexplorerId: 121341234, type: 'neighborhood' },
  { name: 'Parque Chas', url: 'parque-chas', telexplorerId: 121341211, type: 'neighborhood' }, // Para Telexplorer Parque Chas es Agronomía
  { name: 'Parque Patricios', url: 'parque-patricios', telexplorerId: 121341235, type: 'neighborhood' },
  { name: 'Puerto Madero', url: 'puerto-madero', telexplorerId: null, type: 'neighborhood' }, // No aparece en Telexplorer
  { name: 'Recoleta', url: 'recoleta', telexplorerId: 121341238, type: 'neighborhood' },
  { name: 'Retiro', url: 'retiro', telexplorerId: 121341239, type: 'neighborhood' },
  { name: 'Saavedra', url: 'saavedra', telexplorerId: 121341240, type: 'neighborhood' },
  { name: 'San Cristóbal', url: 'san-cristobal', telexplorerId: 121341241, type: 'neighborhood' },
  { name: 'San Nicolás', url: 'san-nicolás', telexplorerId: 121341242, type: 'neighborhood' },
  { name: 'San Telmo', url: 'san-telmo', telexplorerId: 121341243, type: 'neighborhood' },
  { name: 'Vélez Sarsfield', url: 'villa-del-parque', telexplorerId: 121341244, type: 'neighborhood' },
  { name: 'Versalles', url: 'versalles', telexplorerId: 121341245, type: 'neighborhood' },
  { name: 'Villa Crespo', url: 'villa-crespo', telexplorerId: 121341246, type: 'neighborhood' },
  { name: 'Villa Devoto', url: 'villa-devoto', telexplorerId: 121341248, type: 'neighborhood' },
  { name: 'Villa General Mitre', url: 'villa-general-mitre', telexplorerId: 121341249, type: 'neighborhood' },
  { name: 'Villa Lugano', url: 'villa-lugano', telexplorerId: 121341250, type: 'neighborhood' },
  { name: 'Villa Luro', url: 'villa-luro', telexplorerId: 121341251, type: 'neighborhood' },
  { name: 'Villa Ortúzar', url: 'villa-ortuzar', telexplorerId: 121341252, type: 'neighborhood' },
  { name: 'Villa Pueyrredón', url: 'villa-pueyrredon', telexplorerId: 121341253, type: 'neighborhood' },
  { name: 'Villa Real', url: 'villa-real', telexplorerId: null, type: 'neighborhood' }, // No aparece en Telexplorer
  { name: 'Villa Riachuelo', url: 'villa-riachuelo', telexplorerId: 121341255, type: 'neighborhood' },
  { name: 'Villa Santa Rita', url: 'villa-santa-rita', telexplorerId: 121341256, type: 'neighborhood' },
  { name: 'Villa Soldati', url: 'villa-soldati', telexplorerId: 121341257, type: 'neighborhood' },
  { name: 'Villa Urquiza', url: 'villa-urquiza', telexplorerId: 121341258, type: 'neighborhood' },
  { name: 'Villa del Parque', url: 'villa-del-parque', telexplorerId: 121341247, type: 'neighborhood' }
]

export default neighborhoods
